services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teebay
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/teebay"
    ports:
      - "4000:4000"
    restart: on-failure
    command: sh -c "npx prisma migrate deploy && npm run dev"

  frontend:
    build: ./client/my-app
    ports:
      - "5173:5173"
    env_file:
      - ./client/my-app/.env
    depends_on:
      - backend

volumes:
  db_data:
